"""quant数据表

Revision ID: 1ffe8d8466be
Revises: 
Create Date: 2026-01-20 18:11:48.870177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ffe8d8466be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fa_quant_concepts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='概念名称（如：人工智能、芯片、5G）'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='概念代码（如：AI、CHIP、5G）'),
    sa.Column('sort', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='排名'),
    sa.Column('latest_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True, comment='最新价'),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True, comment='涨跌额'),
    sa.Column('change_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='涨跌幅'),
    sa.Column('total_market_cap', sa.Numeric(precision=20, scale=2), server_default='0', nullable=True, comment='总市值'),
    sa.Column('turnover_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='换手率'),
    sa.Column('up_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='上涨家数'),
    sa.Column('down_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='下跌家数'),
    sa.Column('leading_stock', sa.String(length=50), server_default='', nullable=True, comment='领涨股票'),
    sa.Column('leading_stock_change', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='领涨股票涨跌幅'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='概念描述'),
    sa.Column('status', mysql.INTEGER(unsigned=True), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='概念表，存储股票概念标签信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_concepts_code'), 'fa_quant_concepts', ['code'], unique=True)
    op.create_index(op.f('ix_fa_quant_concepts_created_at'), 'fa_quant_concepts', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_concepts_name'), 'fa_quant_concepts', ['name'], unique=True)
    op.create_index(op.f('ix_fa_quant_concepts_updated_at'), 'fa_quant_concepts', ['updated_at'], unique=False)
    op.create_table('fa_quant_industrys',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='行业名称（如：电子化学品、银行、房地产）'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='行业代码（如：BK0433、BK0001）'),
    sa.Column('sort', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='排名'),
    sa.Column('latest_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True, comment='最新价'),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True, comment='涨跌额'),
    sa.Column('change_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='涨跌幅'),
    sa.Column('total_market_cap', sa.Numeric(precision=20, scale=2), server_default='0', nullable=True, comment='总市值'),
    sa.Column('turnover_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='换手率'),
    sa.Column('up_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='上涨家数'),
    sa.Column('down_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='下跌家数'),
    sa.Column('leading_stock', sa.String(length=50), server_default='', nullable=True, comment='领涨股票'),
    sa.Column('leading_stock_change', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='领涨股票涨跌幅'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='行业描述'),
    sa.Column('status', mysql.INTEGER(unsigned=True), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='行业表，存储股票行业分类信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_industrys_code'), 'fa_quant_industrys', ['code'], unique=True)
    op.create_index(op.f('ix_fa_quant_industrys_created_at'), 'fa_quant_industrys', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_industrys_name'), 'fa_quant_industrys', ['name'], unique=True)
    op.create_index(op.f('ix_fa_quant_industrys_updated_at'), 'fa_quant_industrys', ['updated_at'], unique=False)
    op.create_table('fa_quant_stock_kline1ds',
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高价'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低价'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('stock_id', 'trade_date'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='日K线数据表，存储股票日K线数据',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fa_quant_stock_kline1ds_date_stock', 'fa_quant_stock_kline1ds', ['trade_date', 'stock_id'], unique=False)
    op.create_table('fa_quant_concept_logs',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('concept_id', mysql.INTEGER(unsigned=True), nullable=False, comment='关联的概念ID'),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期（年月日）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='概念名称（如：人工智能、芯片、5G）'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='概念代码（如：AI、CHIP、5G）'),
    sa.Column('sort', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='排名'),
    sa.Column('latest_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True, comment='最新价'),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True, comment='涨跌额'),
    sa.Column('change_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='涨跌幅'),
    sa.Column('total_market_cap', sa.Numeric(precision=20, scale=2), server_default='0', nullable=True, comment='总市值'),
    sa.Column('turnover_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='换手率'),
    sa.Column('up_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='上涨家数'),
    sa.Column('down_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='下跌家数'),
    sa.Column('leading_stock', sa.String(length=50), server_default='', nullable=True, comment='领涨股票'),
    sa.Column('leading_stock_change', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='领涨股票涨跌幅'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='概念描述'),
    sa.Column('status', mysql.INTEGER(unsigned=True), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['concept_id'], ['fa_quant_concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='概念历史记录表，存储概念数据的变更历史记录',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_concept_logs_code'), 'fa_quant_concept_logs', ['code'], unique=False)
    op.create_index(op.f('ix_fa_quant_concept_logs_concept_id'), 'fa_quant_concept_logs', ['concept_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_concept_logs_created_at'), 'fa_quant_concept_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_concept_logs_name'), 'fa_quant_concept_logs', ['name'], unique=False)
    op.create_index(op.f('ix_fa_quant_concept_logs_record_date'), 'fa_quant_concept_logs', ['record_date'], unique=False)
    op.create_index(op.f('ix_fa_quant_concept_logs_updated_at'), 'fa_quant_concept_logs', ['updated_at'], unique=False)
    op.create_table('fa_quant_industry_logs',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('industry_id', mysql.INTEGER(unsigned=True), nullable=False, comment='关联的行业ID'),
    sa.Column('record_date', sa.Date(), nullable=False, comment='记录日期（年月日）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='行业名称（如：电子化学品、银行、房地产）'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='行业代码（如：BK0433、BK0001）'),
    sa.Column('sort', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='排名'),
    sa.Column('latest_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True, comment='最新价'),
    sa.Column('change_amount', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True, comment='涨跌额'),
    sa.Column('change_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='涨跌幅'),
    sa.Column('total_market_cap', sa.Numeric(precision=20, scale=2), server_default='0', nullable=True, comment='总市值'),
    sa.Column('turnover_rate', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='换手率'),
    sa.Column('up_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='上涨家数'),
    sa.Column('down_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='下跌家数'),
    sa.Column('leading_stock', sa.String(length=50), server_default='', nullable=True, comment='领涨股票'),
    sa.Column('leading_stock_change', sa.Numeric(precision=5, scale=2), server_default='0', nullable=True, comment='领涨股票涨跌幅'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='行业描述'),
    sa.Column('status', mysql.INTEGER(unsigned=True), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['industry_id'], ['fa_quant_industrys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='行业历史记录表，存储行业数据的变更历史记录',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_industry_logs_code'), 'fa_quant_industry_logs', ['code'], unique=False)
    op.create_index(op.f('ix_fa_quant_industry_logs_created_at'), 'fa_quant_industry_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_industry_logs_industry_id'), 'fa_quant_industry_logs', ['industry_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_industry_logs_name'), 'fa_quant_industry_logs', ['name'], unique=False)
    op.create_index(op.f('ix_fa_quant_industry_logs_record_date'), 'fa_quant_industry_logs', ['record_date'], unique=False)
    op.create_index(op.f('ix_fa_quant_industry_logs_updated_at'), 'fa_quant_industry_logs', ['updated_at'], unique=False)
    op.create_table('fa_quant_stocks',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_code', sa.String(length=20), nullable=False, comment='股票代码（如：600000.SH、000001.SZ、00700.HK、AAPL.US）'),
    sa.Column('stock_name', sa.String(length=100), server_default='', nullable=False, comment='股票名称'),
    sa.Column('market', sa.SmallInteger(), server_default='0', nullable=False, comment='市场类型（1=上海(SH)、2=深圳(SZ)、3=北京(BJ)、4=港股(HK)、5=美股(US)）'),
    sa.Column('exchange', sa.SmallInteger(), server_default='0', nullable=True, comment='交易所代码（1=上海证券交易所(SSE)、2=深圳证券交易所(SZSE)、3=北京证券交易所(BSE)、4=香港交易所(HKEX)、5=纳斯达克(NASDAQ)、6=纽约证券交易所(NYSE)、7=美国证券交易所(AMEX)）'),
    sa.Column('industry_id', mysql.INTEGER(unsigned=True), nullable=True, comment='所属行业ID'),
    sa.Column('list_status', sa.SmallInteger(), server_default='1', nullable=False, comment='上市状态（0=未上市、1=已上市、2=退市、3=暂停上市）'),
    sa.Column('trade_status', sa.SmallInteger(), server_default='1', nullable=False, comment='交易状态（0=停牌、1=正常交易、2=特别处理）'),
    sa.Column('is_st', sa.SmallInteger(), server_default='0', nullable=False, comment='是否ST股（0=否、1=是）'),
    sa.Column('stock_type', sa.SmallInteger(), nullable=True, comment='股票类型（1=主板、2=创业板、3=科创板、4=北交所）'),
    sa.Column('total_market_cap', mysql.DECIMAL(precision=15, scale=2), nullable=True, comment='总市值（单位：亿元）'),
    sa.Column('circulating_market_cap', mysql.DECIMAL(precision=15, scale=2), nullable=True, comment='流通市值（单位：亿元）'),
    sa.Column('pe_ratio', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='市盈率（动态）'),
    sa.Column('pb_ratio', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='市净率'),
    sa.Column('total_shares', mysql.DECIMAL(precision=15, scale=2), nullable=True, comment='总股本（万股）'),
    sa.Column('circulating_shares', mysql.DECIMAL(precision=15, scale=2), nullable=True, comment='流通股本（万股）'),
    sa.Column('latest_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最新价'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='今开'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='昨收'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('change_speed', mysql.DECIMAL(precision=8, scale=4), nullable=True, comment='涨速'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('volume_ratio', mysql.DECIMAL(precision=8, scale=2), nullable=True, comment='量比'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_5min', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='5分钟涨跌（%）'),
    sa.Column('change_60day', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='60日涨跌幅（%）'),
    sa.Column('change_ytd', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='年初至今涨跌幅（%）'),
    sa.Column('list_date', sa.Date(), nullable=True, comment='上市日期'),
    sa.Column('delist_date', sa.Date(), nullable=True, comment='退市日期'),
    sa.Column('ipo_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='发行价格'),
    sa.Column('ipo_shares', mysql.DECIMAL(precision=15, scale=2), nullable=True, comment='发行数量（万股）'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='股票描述/简介'),
    sa.Column('website', sa.String(length=200), nullable=True, comment='官方网站'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='公司Logo URL'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['industry_id'], ['fa_quant_industrys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='统一股票表，存储所有市场股票基础信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stocks_created_at'), 'fa_quant_stocks', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stocks_industry_id'), 'fa_quant_stocks', ['industry_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stocks_list_date'), 'fa_quant_stocks', ['list_date'], unique=False)
    op.create_index(op.f('ix_fa_quant_stocks_list_status'), 'fa_quant_stocks', ['list_status'], unique=False)
    op.create_index(op.f('ix_fa_quant_stocks_market'), 'fa_quant_stocks', ['market'], unique=False)
    op.create_index(op.f('ix_fa_quant_stocks_stock_code'), 'fa_quant_stocks', ['stock_code'], unique=True)
    op.create_index(op.f('ix_fa_quant_stocks_stock_type'), 'fa_quant_stocks', ['stock_type'], unique=False)
    op.create_index(op.f('ix_fa_quant_stocks_trade_status'), 'fa_quant_stocks', ['trade_status'], unique=False)
    op.create_index(op.f('ix_fa_quant_stocks_updated_at'), 'fa_quant_stocks', ['updated_at'], unique=False)
    op.create_table('fa_quant_stock_concepts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('concept_id', mysql.INTEGER(unsigned=True), nullable=False, comment='概念ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['concept_id'], ['fa_quant_concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_id'], ['fa_quant_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='股票-概念关联表，存储股票与概念的多对多关联关系',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stock_concepts_concept_id'), 'fa_quant_stock_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_concepts_created_at'), 'fa_quant_stock_concepts', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_concepts_stock_id'), 'fa_quant_stock_concepts', ['stock_id'], unique=False)
    op.create_table('fa_quant_stock_kline15ms',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('trade_time', sa.DateTime(), nullable=False, comment='交易时间'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高价'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低价'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['stock_id'], ['fa_quant_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='15分钟K线数据表，存储股票15分钟K线数据',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stock_kline15ms_created_at'), 'fa_quant_stock_kline15ms', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline15ms_stock_id'), 'fa_quant_stock_kline15ms', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline15ms_trade_time'), 'fa_quant_stock_kline15ms', ['trade_time'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline15ms_updated_at'), 'fa_quant_stock_kline15ms', ['updated_at'], unique=False)
    op.create_table('fa_quant_stock_kline1m_mins',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('trade_time', sa.DateTime(), nullable=False, comment='交易时间'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高价'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低价'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['stock_id'], ['fa_quant_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='1分钟K线数据表，存储股票1分钟K线数据',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stock_kline1m_mins_created_at'), 'fa_quant_stock_kline1m_mins', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1m_mins_stock_id'), 'fa_quant_stock_kline1m_mins', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1m_mins_trade_time'), 'fa_quant_stock_kline1m_mins', ['trade_time'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1m_mins_updated_at'), 'fa_quant_stock_kline1m_mins', ['updated_at'], unique=False)
    op.create_table('fa_quant_stock_kline1ms',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期（月结束日期）'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高价'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低价'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['stock_id'], ['fa_quant_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='月K线数据表，存储股票月K线数据',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stock_kline1ms_created_at'), 'fa_quant_stock_kline1ms', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1ms_stock_id'), 'fa_quant_stock_kline1ms', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1ms_trade_date'), 'fa_quant_stock_kline1ms', ['trade_date'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1ms_updated_at'), 'fa_quant_stock_kline1ms', ['updated_at'], unique=False)
    op.create_table('fa_quant_stock_kline1ws',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期（周结束日期）'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高价'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低价'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['stock_id'], ['fa_quant_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='周K线数据表，存储股票周K线数据',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stock_kline1ws_created_at'), 'fa_quant_stock_kline1ws', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1ws_stock_id'), 'fa_quant_stock_kline1ws', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1ws_trade_date'), 'fa_quant_stock_kline1ws', ['trade_date'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline1ws_updated_at'), 'fa_quant_stock_kline1ws', ['updated_at'], unique=False)
    op.create_table('fa_quant_stock_kline30ms',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('trade_time', sa.DateTime(), nullable=False, comment='交易时间'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高价'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低价'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['stock_id'], ['fa_quant_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='30分钟K线数据表，存储股票30分钟K线数据',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stock_kline30ms_created_at'), 'fa_quant_stock_kline30ms', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline30ms_stock_id'), 'fa_quant_stock_kline30ms', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline30ms_trade_time'), 'fa_quant_stock_kline30ms', ['trade_time'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline30ms_updated_at'), 'fa_quant_stock_kline30ms', ['updated_at'], unique=False)
    op.create_table('fa_quant_stock_kline5ms',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('trade_time', sa.DateTime(), nullable=False, comment='交易时间'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高价'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低价'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['stock_id'], ['fa_quant_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='5分钟K线数据表，存储股票5分钟K线数据',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stock_kline5ms_created_at'), 'fa_quant_stock_kline5ms', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline5ms_stock_id'), 'fa_quant_stock_kline5ms', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline5ms_trade_time'), 'fa_quant_stock_kline5ms', ['trade_time'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline5ms_updated_at'), 'fa_quant_stock_kline5ms', ['updated_at'], unique=False)
    op.create_table('fa_quant_stock_kline60ms',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('stock_id', mysql.INTEGER(unsigned=True), nullable=False, comment='股票ID'),
    sa.Column('trade_time', sa.DateTime(), nullable=False, comment='交易时间'),
    sa.Column('open_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='开盘价'),
    sa.Column('high_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最高价'),
    sa.Column('low_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='最低价'),
    sa.Column('close_price', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='收盘价'),
    sa.Column('volume', mysql.DECIMAL(precision=20, scale=0), nullable=True, comment='成交量'),
    sa.Column('amount', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('turnover_rate', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='换手率（%）'),
    sa.Column('change_percent', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='涨跌幅（%）'),
    sa.Column('amplitude', mysql.DECIMAL(precision=10, scale=4), nullable=True, comment='振幅（%）'),
    sa.Column('change_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True, comment='涨跌额'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='记录状态（0=禁用、1=启用）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['stock_id'], ['fa_quant_stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='60分钟K线数据表，存储股票60分钟K线数据',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_quant_stock_kline60ms_created_at'), 'fa_quant_stock_kline60ms', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline60ms_stock_id'), 'fa_quant_stock_kline60ms', ['stock_id'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline60ms_trade_time'), 'fa_quant_stock_kline60ms', ['trade_time'], unique=False)
    op.create_index(op.f('ix_fa_quant_stock_kline60ms_updated_at'), 'fa_quant_stock_kline60ms', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fa_quant_stock_kline60ms_updated_at'), table_name='fa_quant_stock_kline60ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline60ms_trade_time'), table_name='fa_quant_stock_kline60ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline60ms_stock_id'), table_name='fa_quant_stock_kline60ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline60ms_created_at'), table_name='fa_quant_stock_kline60ms')
    op.drop_table('fa_quant_stock_kline60ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline5ms_updated_at'), table_name='fa_quant_stock_kline5ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline5ms_trade_time'), table_name='fa_quant_stock_kline5ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline5ms_stock_id'), table_name='fa_quant_stock_kline5ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline5ms_created_at'), table_name='fa_quant_stock_kline5ms')
    op.drop_table('fa_quant_stock_kline5ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline30ms_updated_at'), table_name='fa_quant_stock_kline30ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline30ms_trade_time'), table_name='fa_quant_stock_kline30ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline30ms_stock_id'), table_name='fa_quant_stock_kline30ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline30ms_created_at'), table_name='fa_quant_stock_kline30ms')
    op.drop_table('fa_quant_stock_kline30ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline1ws_updated_at'), table_name='fa_quant_stock_kline1ws')
    op.drop_index(op.f('ix_fa_quant_stock_kline1ws_trade_date'), table_name='fa_quant_stock_kline1ws')
    op.drop_index(op.f('ix_fa_quant_stock_kline1ws_stock_id'), table_name='fa_quant_stock_kline1ws')
    op.drop_index(op.f('ix_fa_quant_stock_kline1ws_created_at'), table_name='fa_quant_stock_kline1ws')
    op.drop_table('fa_quant_stock_kline1ws')
    op.drop_index(op.f('ix_fa_quant_stock_kline1ms_updated_at'), table_name='fa_quant_stock_kline1ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline1ms_trade_date'), table_name='fa_quant_stock_kline1ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline1ms_stock_id'), table_name='fa_quant_stock_kline1ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline1ms_created_at'), table_name='fa_quant_stock_kline1ms')
    op.drop_table('fa_quant_stock_kline1ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline1m_mins_updated_at'), table_name='fa_quant_stock_kline1m_mins')
    op.drop_index(op.f('ix_fa_quant_stock_kline1m_mins_trade_time'), table_name='fa_quant_stock_kline1m_mins')
    op.drop_index(op.f('ix_fa_quant_stock_kline1m_mins_stock_id'), table_name='fa_quant_stock_kline1m_mins')
    op.drop_index(op.f('ix_fa_quant_stock_kline1m_mins_created_at'), table_name='fa_quant_stock_kline1m_mins')
    op.drop_table('fa_quant_stock_kline1m_mins')
    op.drop_index(op.f('ix_fa_quant_stock_kline15ms_updated_at'), table_name='fa_quant_stock_kline15ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline15ms_trade_time'), table_name='fa_quant_stock_kline15ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline15ms_stock_id'), table_name='fa_quant_stock_kline15ms')
    op.drop_index(op.f('ix_fa_quant_stock_kline15ms_created_at'), table_name='fa_quant_stock_kline15ms')
    op.drop_table('fa_quant_stock_kline15ms')
    op.drop_index(op.f('ix_fa_quant_stock_concepts_stock_id'), table_name='fa_quant_stock_concepts')
    op.drop_index(op.f('ix_fa_quant_stock_concepts_created_at'), table_name='fa_quant_stock_concepts')
    op.drop_index(op.f('ix_fa_quant_stock_concepts_concept_id'), table_name='fa_quant_stock_concepts')
    op.drop_table('fa_quant_stock_concepts')
    op.drop_index(op.f('ix_fa_quant_stocks_updated_at'), table_name='fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_stocks_trade_status'), table_name='fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_stocks_stock_type'), table_name='fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_stocks_stock_code'), table_name='fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_stocks_market'), table_name='fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_stocks_list_status'), table_name='fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_stocks_list_date'), table_name='fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_stocks_industry_id'), table_name='fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_stocks_created_at'), table_name='fa_quant_stocks')
    op.drop_table('fa_quant_stocks')
    op.drop_index(op.f('ix_fa_quant_industry_logs_updated_at'), table_name='fa_quant_industry_logs')
    op.drop_index(op.f('ix_fa_quant_industry_logs_record_date'), table_name='fa_quant_industry_logs')
    op.drop_index(op.f('ix_fa_quant_industry_logs_name'), table_name='fa_quant_industry_logs')
    op.drop_index(op.f('ix_fa_quant_industry_logs_industry_id'), table_name='fa_quant_industry_logs')
    op.drop_index(op.f('ix_fa_quant_industry_logs_created_at'), table_name='fa_quant_industry_logs')
    op.drop_index(op.f('ix_fa_quant_industry_logs_code'), table_name='fa_quant_industry_logs')
    op.drop_table('fa_quant_industry_logs')
    op.drop_index(op.f('ix_fa_quant_concept_logs_updated_at'), table_name='fa_quant_concept_logs')
    op.drop_index(op.f('ix_fa_quant_concept_logs_record_date'), table_name='fa_quant_concept_logs')
    op.drop_index(op.f('ix_fa_quant_concept_logs_name'), table_name='fa_quant_concept_logs')
    op.drop_index(op.f('ix_fa_quant_concept_logs_created_at'), table_name='fa_quant_concept_logs')
    op.drop_index(op.f('ix_fa_quant_concept_logs_concept_id'), table_name='fa_quant_concept_logs')
    op.drop_index(op.f('ix_fa_quant_concept_logs_code'), table_name='fa_quant_concept_logs')
    op.drop_table('fa_quant_concept_logs')
    op.drop_index('idx_fa_quant_stock_kline1ds_date_stock', table_name='fa_quant_stock_kline1ds')
    op.drop_table('fa_quant_stock_kline1ds')
    op.drop_index(op.f('ix_fa_quant_industrys_updated_at'), table_name='fa_quant_industrys')
    op.drop_index(op.f('ix_fa_quant_industrys_name'), table_name='fa_quant_industrys')
    op.drop_index(op.f('ix_fa_quant_industrys_created_at'), table_name='fa_quant_industrys')
    op.drop_index(op.f('ix_fa_quant_industrys_code'), table_name='fa_quant_industrys')
    op.drop_table('fa_quant_industrys')
    op.drop_index(op.f('ix_fa_quant_concepts_updated_at'), table_name='fa_quant_concepts')
    op.drop_index(op.f('ix_fa_quant_concepts_name'), table_name='fa_quant_concepts')
    op.drop_index(op.f('ix_fa_quant_concepts_created_at'), table_name='fa_quant_concepts')
    op.drop_index(op.f('ix_fa_quant_concepts_code'), table_name='fa_quant_concepts')
    op.drop_table('fa_quant_concepts')
    # ### end Alembic commands ###
