"""内容管理相关表

Revision ID: eaadc032a463
Revises: 
Create Date: 2026-02-05 18:09:15.169801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eaadc032a463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fa_content_categorys',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名称'),
    sa.Column('slug', sa.String(length=50), nullable=False, comment='分类别名'),
    sa.Column('parent_id', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='父分类ID'),
    sa.Column('sort', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='排序'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态: 0=禁用, 1=启用'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='分类描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='文章分类表，存储文章分类信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_content_categorys_created_at'), 'fa_content_categorys', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_content_categorys_parent_id'), 'fa_content_categorys', ['parent_id'], unique=False)
    op.create_index(op.f('ix_fa_content_categorys_slug'), 'fa_content_categorys', ['slug'], unique=True)
    op.create_index(op.f('ix_fa_content_categorys_status'), 'fa_content_categorys', ['status'], unique=False)
    op.create_index(op.f('ix_fa_content_categorys_updated_at'), 'fa_content_categorys', ['updated_at'], unique=False)
    op.create_table('fa_content_platform_accounts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='平台标识：zhihu, juejin, csdn等'),
    sa.Column('account_name', sa.String(length=50), nullable=False, comment='账号名称'),
    sa.Column('cookies', sa.Text(), nullable=False, comment='Cookie信息（JSON格式加密存储）'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器UA'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态: 0=失效, 1=有效, 2=过期'),
    sa.Column('last_verified', sa.DateTime(), nullable=True, comment='最后验证时间'),
    sa.Column('created_by', mysql.INTEGER(unsigned=True), nullable=False, comment='创建人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='第三方平台账号表，存储第三方平台账号信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_content_platform_accounts_created_at'), 'fa_content_platform_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_content_platform_accounts_platform'), 'fa_content_platform_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_fa_content_platform_accounts_status'), 'fa_content_platform_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_fa_content_platform_accounts_updated_at'), 'fa_content_platform_accounts', ['updated_at'], unique=False)
    op.create_table('fa_content_tags',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='标签名称'),
    sa.Column('slug', sa.String(length=30), nullable=False, comment='标签别名'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='标签颜色'),
    sa.Column('sort', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='排序'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态: 0=禁用, 1=启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='文章标签表，存储文章标签信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_content_tags_created_at'), 'fa_content_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_content_tags_name'), 'fa_content_tags', ['name'], unique=True)
    op.create_index(op.f('ix_fa_content_tags_slug'), 'fa_content_tags', ['slug'], unique=True)
    op.create_index(op.f('ix_fa_content_tags_status'), 'fa_content_tags', ['status'], unique=False)
    op.create_index(op.f('ix_fa_content_tags_updated_at'), 'fa_content_tags', ['updated_at'], unique=False)
    op.create_table('fa_content_articles',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文章标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容（Markdown格式）'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='文章摘要'),
    sa.Column('cover_image_id', mysql.INTEGER(unsigned=True), nullable=True, comment='封面图片ID'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False, comment='状态: 0=草稿, 1=已发布, 2=审核中, 3=发布失败'),
    sa.Column('author_id', mysql.INTEGER(unsigned=True), nullable=False, comment='作者ID'),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=True, comment='分类ID'),
    sa.Column('view_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='浏览次数'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['fa_content_categorys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='文章表，存储文章信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_content_articles_created_at'), 'fa_content_articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_content_articles_status'), 'fa_content_articles', ['status'], unique=False)
    op.create_index(op.f('ix_fa_content_articles_updated_at'), 'fa_content_articles', ['updated_at'], unique=False)
    op.create_table('fa_content_article_tags',
    sa.Column('article_id', mysql.INTEGER(unsigned=True), nullable=False, comment='文章ID'),
    sa.Column('tag_id', mysql.INTEGER(unsigned=True), nullable=False, comment='标签ID'),
    sa.ForeignKeyConstraint(['article_id'], ['fa_content_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['fa_content_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='文章标签关联表，存储文章与标签的多对多关系',
    mysql_engine='InnoDB'
    )
    op.create_table('fa_content_publish_logs',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('article_id', mysql.INTEGER(unsigned=True), nullable=False, comment='文章ID'),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='发布平台'),
    sa.Column('platform_article_id', sa.String(length=50), nullable=True, comment='平台文章ID'),
    sa.Column('platform_url', sa.String(length=200), nullable=True, comment='平台文章链接'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False, comment='状态: 0=待发布, 1=发布中, 2=成功, 3=失败'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('retry_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='重试次数'),
    sa.Column('task_id', sa.String(length=50), nullable=True, comment='Celery任务ID'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['article_id'], ['fa_content_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='文章发布日志表，存储文章发布日志信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_content_publish_logs_created_at'), 'fa_content_publish_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_content_publish_logs_status'), 'fa_content_publish_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fa_content_publish_logs_status'), table_name='fa_content_publish_logs')
    op.drop_index(op.f('ix_fa_content_publish_logs_created_at'), table_name='fa_content_publish_logs')
    op.drop_table('fa_content_publish_logs')
    op.drop_table('fa_content_article_tags')
    op.drop_index(op.f('ix_fa_content_articles_updated_at'), table_name='fa_content_articles')
    op.drop_index(op.f('ix_fa_content_articles_status'), table_name='fa_content_articles')
    op.drop_index(op.f('ix_fa_content_articles_created_at'), table_name='fa_content_articles')
    op.drop_table('fa_content_articles')
    op.drop_index(op.f('ix_fa_content_tags_updated_at'), table_name='fa_content_tags')
    op.drop_index(op.f('ix_fa_content_tags_status'), table_name='fa_content_tags')
    op.drop_index(op.f('ix_fa_content_tags_slug'), table_name='fa_content_tags')
    op.drop_index(op.f('ix_fa_content_tags_name'), table_name='fa_content_tags')
    op.drop_index(op.f('ix_fa_content_tags_created_at'), table_name='fa_content_tags')
    op.drop_table('fa_content_tags')
    op.drop_index(op.f('ix_fa_content_platform_accounts_updated_at'), table_name='fa_content_platform_accounts')
    op.drop_index(op.f('ix_fa_content_platform_accounts_status'), table_name='fa_content_platform_accounts')
    op.drop_index(op.f('ix_fa_content_platform_accounts_platform'), table_name='fa_content_platform_accounts')
    op.drop_index(op.f('ix_fa_content_platform_accounts_created_at'), table_name='fa_content_platform_accounts')
    op.drop_table('fa_content_platform_accounts')
    op.drop_index(op.f('ix_fa_content_categorys_updated_at'), table_name='fa_content_categorys')
    op.drop_index(op.f('ix_fa_content_categorys_status'), table_name='fa_content_categorys')
    op.drop_index(op.f('ix_fa_content_categorys_slug'), table_name='fa_content_categorys')
    op.drop_index(op.f('ix_fa_content_categorys_parent_id'), table_name='fa_content_categorys')
    op.drop_index(op.f('ix_fa_content_categorys_created_at'), table_name='fa_content_categorys')
    op.drop_table('fa_content_categorys')
    # ### end Alembic commands ###
