"""content数据表

Revision ID: dde45198a0a5
Revises: 791b21a7b4f9
Create Date: 2026-03-02 10:27:30.617714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dde45198a0a5'
down_revision = '791b21a7b4f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fa_content_publish_logs', sa.Column('platform_account_id', mysql.INTEGER(unsigned=True), nullable=True, comment='平台账号ID'))
    op.create_foreign_key(None, 'fa_content_publish_logs', 'fa_content_platform_accounts', ['platform_account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fa_content_publish_logs', type_='foreignkey')
    op.drop_column('fa_content_publish_logs', 'platform_account_id')
    # ### end Alembic commands ###
