"""content数据表

Revision ID: 791b21a7b4f9
Revises: efc7e1f2f6e2
Create Date: 2026-02-28 18:12:09.082618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '791b21a7b4f9'
down_revision = 'efc7e1f2f6e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fa_content_topics', sa.Column('article_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='文章数量'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fa_content_topics', 'article_count')
    # ### end Alembic commands ###
