"""content数据表

Revision ID: 5baeee64e015
Revises: 12fca133eae6
Create Date: 2026-02-28 16:05:47.656412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5baeee64e015'
down_revision = '12fca133eae6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'fa_content_article_tags',
        existing_comment='文章标签关联表，存储文章与标签的多对多关系',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_articles',
        existing_comment='文章表，存储文章信息',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_categorys',
        existing_comment='文章分类表，存储文章分类信息',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_platform_accounts',
        existing_comment='第三方平台账号表，存储第三方平台账号信息',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_publish_logs',
        existing_comment='文章发布日志表，存储文章发布日志信息',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_tags',
        existing_comment='文章标签表，存储文章标签信息',
        schema=None
    )
    op.add_column('fa_content_topics', sa.Column('zhihu_content', sa.Text(), nullable=True, comment='知乎问题内容（JSON格式）：{title, description, url, answers: [{author, content}], fetched_at, answer_count}'))
    op.add_column('fa_content_topics', sa.Column('zhihu_content_updated_at', sa.DateTime(), nullable=True, comment='知乎内容更新时间'))
    op.drop_table_comment(
        'fa_content_topics',
        existing_comment='话题/问题表，存储从第三方平台抓取的话题/问题信息',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'fa_content_topics',
        '话题/问题表，存储从第三方平台抓取的话题/问题信息',
        existing_comment=None,
        schema=None
    )
    op.drop_column('fa_content_topics', 'zhihu_content_updated_at')
    op.drop_column('fa_content_topics', 'zhihu_content')
    op.create_table_comment(
        'fa_content_tags',
        '文章标签表，存储文章标签信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_publish_logs',
        '文章发布日志表，存储文章发布日志信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_platform_accounts',
        '第三方平台账号表，存储第三方平台账号信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_categorys',
        '文章分类表，存储文章分类信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_articles',
        '文章表，存储文章信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_article_tags',
        '文章标签关联表，存储文章与标签的多对多关系',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
