"""content数据表

Revision ID: efc7e1f2f6e2
Revises: 5baeee64e015
Create Date: 2026-02-28 17:11:36.002872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efc7e1f2f6e2'
down_revision = '5baeee64e015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fa_content_articles', sa.Column('topic_id', mysql.INTEGER(unsigned=True), nullable=True, comment='话题ID'))
    op.create_foreign_key(None, 'fa_content_articles', 'fa_content_topics', ['topic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fa_content_articles', type_='foreignkey')
    op.drop_column('fa_content_articles', 'topic_id')
    # ### end Alembic commands ###
