"""新增话题/问题表

Revision ID: 319f159a6141
Revises: eaadc032a463
Create Date: 2026-02-10 10:18:23.115312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '319f159a6141'
down_revision = 'eaadc032a463'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fa_content_topics',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='平台标识：zhihu'),
    sa.Column('platform_question_id', sa.String(length=50), nullable=False, comment='平台问题ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='问题标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='问题描述'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='问题链接'),
    sa.Column('view_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='浏览量'),
    sa.Column('answer_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='回答数'),
    sa.Column('follower_count', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='关注者数'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='分类/话题标签'),
    sa.Column('hot_score', mysql.INTEGER(unsigned=True), nullable=True, comment='热度分数'),
    sa.Column('author_name', sa.String(length=100), nullable=True, comment='提问者昵称'),
    sa.Column('author_url', sa.String(length=200), nullable=True, comment='提问者主页'),
    sa.Column('status', sa.SmallInteger(), server_default='0', nullable=False, comment='状态: 0=未使用, 1=已使用, 2=已收藏'),
    sa.Column('fetched_at', sa.DateTime(), nullable=False, comment='抓取时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='话题/问题表，存储从第三方平台抓取的话题/问题信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_content_topics_answer_count'), 'fa_content_topics', ['answer_count'], unique=False)
    op.create_index(op.f('ix_fa_content_topics_category'), 'fa_content_topics', ['category'], unique=False)
    op.create_index(op.f('ix_fa_content_topics_fetched_at'), 'fa_content_topics', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_fa_content_topics_hot_score'), 'fa_content_topics', ['hot_score'], unique=False)
    op.create_index(op.f('ix_fa_content_topics_platform'), 'fa_content_topics', ['platform'], unique=False)
    op.create_index(op.f('ix_fa_content_topics_status'), 'fa_content_topics', ['status'], unique=False)
    op.create_index(op.f('ix_fa_content_topics_view_count'), 'fa_content_topics', ['view_count'], unique=False)
    op.drop_table_comment(
        'fa_content_article_tags',
        existing_comment='文章标签关联表，存储文章与标签的多对多关系',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_articles',
        existing_comment='文章表，存储文章信息',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_categorys',
        existing_comment='文章分类表，存储文章分类信息',
        schema=None
    )
    op.alter_column('fa_content_platform_accounts', 'platform',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='平台标识：zhihu',
               existing_comment='平台标识：zhihu, juejin, csdn等',
               existing_nullable=False)
    op.drop_table_comment(
        'fa_content_platform_accounts',
        existing_comment='第三方平台账号表，存储第三方平台账号信息',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_publish_logs',
        existing_comment='文章发布日志表，存储文章发布日志信息',
        schema=None
    )
    op.drop_table_comment(
        'fa_content_tags',
        existing_comment='文章标签表，存储文章标签信息',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'fa_content_tags',
        '文章标签表，存储文章标签信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_publish_logs',
        '文章发布日志表，存储文章发布日志信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_platform_accounts',
        '第三方平台账号表，存储第三方平台账号信息',
        existing_comment=None,
        schema=None
    )
    op.alter_column('fa_content_platform_accounts', 'platform',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=20),
               comment='平台标识：zhihu, juejin, csdn等',
               existing_comment='平台标识：zhihu',
               existing_nullable=False)
    op.create_table_comment(
        'fa_content_categorys',
        '文章分类表，存储文章分类信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_articles',
        '文章表，存储文章信息',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'fa_content_article_tags',
        '文章标签关联表，存储文章与标签的多对多关系',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_fa_content_topics_view_count'), table_name='fa_content_topics')
    op.drop_index(op.f('ix_fa_content_topics_status'), table_name='fa_content_topics')
    op.drop_index(op.f('ix_fa_content_topics_platform'), table_name='fa_content_topics')
    op.drop_index(op.f('ix_fa_content_topics_hot_score'), table_name='fa_content_topics')
    op.drop_index(op.f('ix_fa_content_topics_fetched_at'), table_name='fa_content_topics')
    op.drop_index(op.f('ix_fa_content_topics_category'), table_name='fa_content_topics')
    op.drop_index(op.f('ix_fa_content_topics_answer_count'), table_name='fa_content_topics')
    op.drop_table('fa_content_topics')
    # ### end Alembic commands ###
