"""admin数据表

Revision ID: 385f79955eaa
Revises: 
Create Date: 2026-01-13 12:11:03.508285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '385f79955eaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fa_admin_groups',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False, comment='角色名称'),
    sa.Column('content', sa.String(length=100), server_default='', nullable=True, comment='角色描述'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态:0=禁用,1=启用'),
    sa.Column('rules', sa.TEXT(), nullable=True, comment='菜单规则多个用|隔开'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='角色表，存储系统角色信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_admin_groups_created_at'), 'fa_admin_groups', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_admin_groups_name'), 'fa_admin_groups', ['name'], unique=True)
    op.create_index(op.f('ix_fa_admin_groups_status'), 'fa_admin_groups', ['status'], unique=False)
    op.create_index(op.f('ix_fa_admin_groups_updated_at'), 'fa_admin_groups', ['updated_at'], unique=False)
    op.create_table('fa_admin_rules',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('path', sa.String(length=100), server_default='', nullable=True, comment='路由路径'),
    sa.Column('component', sa.String(length=100), server_default='', nullable=True, comment='组件路径'),
    sa.Column('redirect', sa.String(length=100), server_default='', nullable=True, comment='重定向路径'),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False, comment='菜单名称'),
    sa.Column('type', sa.SmallInteger(), server_default='1', nullable=False, comment='菜单类型:1=模块,2=目录,3=菜单'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='侧边栏显示状态:0=隐藏,1=显示'),
    sa.Column('level', sa.SmallInteger(), server_default='1', nullable=False, comment='级别'),
    sa.Column('icon', sa.String(length=50), server_default='', nullable=True, comment='图标'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=False, comment='父级ID'),
    sa.Column('sort', sa.Integer(), server_default='1', nullable=False, comment='排序'),
    sa.Column('target', sa.String(length=10), server_default='', nullable=False, comment='链接打开方式：_self/_blank'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='菜单表，存储系统菜单信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_admin_rules_created_at'), 'fa_admin_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_admin_rules_pid'), 'fa_admin_rules', ['pid'], unique=False)
    op.create_index(op.f('ix_fa_admin_rules_status'), 'fa_admin_rules', ['status'], unique=False)
    op.create_index(op.f('ix_fa_admin_rules_updated_at'), 'fa_admin_rules', ['updated_at'], unique=False)
    op.create_table('fa_admin_sys_configs',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键（唯一）'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('value_type', sa.String(length=20), nullable=False, comment='值类型(string/int/bool/json)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置说明'),
    sa.Column('group_code', sa.String(length=50), nullable=True, comment='配置分组'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='系统配置表，存储系统配置信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_admin_sys_configs_config_key'), 'fa_admin_sys_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_fa_admin_sys_configs_created_at'), 'fa_admin_sys_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_admin_sys_configs_group_code'), 'fa_admin_sys_configs', ['group_code'], unique=False)
    op.create_index(op.f('ix_fa_admin_sys_configs_updated_at'), 'fa_admin_sys_configs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_fa_admin_sys_configs_value_type'), 'fa_admin_sys_configs', ['value_type'], unique=False)
    op.create_table('fa_admin_admins',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False, comment='管理员姓名'),
    sa.Column('phone', sa.String(length=100), server_default='', nullable=True, comment='手机号'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='账号'),
    sa.Column('password', sa.String(length=191), server_default='', nullable=False, comment='密码'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态:0=禁用,1=启用'),
    sa.Column('group_id', mysql.INTEGER(unsigned=True), nullable=True, comment='所属组ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['group_id'], ['fa_admin_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='管理员表，存储系统管理员信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_admin_admins_created_at'), 'fa_admin_admins', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_admin_admins_status'), 'fa_admin_admins', ['status'], unique=False)
    op.create_index(op.f('ix_fa_admin_admins_updated_at'), 'fa_admin_admins', ['updated_at'], unique=False)
    op.create_index(op.f('ix_fa_admin_admins_username'), 'fa_admin_admins', ['username'], unique=True)
    op.create_table('fa_admin_uploads',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('original_name', sa.String(length=255), server_default='', nullable=False, comment='原始文件名'),
    sa.Column('filename', sa.String(length=255), server_default='', nullable=False, comment='存储文件名'),
    sa.Column('file_path', sa.String(length=500), server_default='', nullable=False, comment='文件存储路径'),
    sa.Column('file_size', mysql.BIGINT(unsigned=True), server_default='0', nullable=False, comment='文件大小（字节）'),
    sa.Column('mime_type', sa.String(length=100), server_default='', nullable=False, comment='MIME类型'),
    sa.Column('file_ext', sa.String(length=20), server_default='', nullable=False, comment='文件扩展名'),
    sa.Column('file_hash', sa.String(length=64), server_default='', nullable=True, comment='文件哈希值（SHA256）'),
    sa.Column('storage_type', sa.String(length=20), server_default='local', nullable=False, comment='存储类型(local/aliyun_oss/tencent_oss/qiniu_oss)'),
    sa.Column('file_type', sa.String(length=50), server_default='other', nullable=False, comment='文件分类:image/document/video/audio/other'),
    sa.Column('admin_id', mysql.INTEGER(unsigned=True), nullable=True, comment='上传者ID'),
    sa.Column('width', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='图片宽度'),
    sa.Column('height', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='图片高度'),
    sa.Column('duration', mysql.INTEGER(unsigned=True), server_default='0', nullable=True, comment='时长（秒）'),
    sa.Column('thumbnail_filename', sa.String(length=255), server_default='', nullable=True, comment='缩略图文件名'),
    sa.Column('thumbnail_path', sa.String(length=500), server_default='', nullable=True, comment='缩略图存储路径'),
    sa.Column('extra_info', sa.String(length=1000), server_default='', nullable=True, comment='扩展信息（JSON）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['admin_id'], ['fa_admin_admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='文件上传表，存储系统文件上传信息',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_fa_admin_uploads_created_at'), 'fa_admin_uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_fa_admin_uploads_file_hash'), 'fa_admin_uploads', ['file_hash'], unique=False)
    op.create_index(op.f('ix_fa_admin_uploads_storage_type'), 'fa_admin_uploads', ['storage_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fa_admin_uploads_storage_type'), table_name='fa_admin_uploads')
    op.drop_index(op.f('ix_fa_admin_uploads_file_hash'), table_name='fa_admin_uploads')
    op.drop_index(op.f('ix_fa_admin_uploads_created_at'), table_name='fa_admin_uploads')
    op.drop_table('fa_admin_uploads')
    op.drop_index(op.f('ix_fa_admin_admins_username'), table_name='fa_admin_admins')
    op.drop_index(op.f('ix_fa_admin_admins_updated_at'), table_name='fa_admin_admins')
    op.drop_index(op.f('ix_fa_admin_admins_status'), table_name='fa_admin_admins')
    op.drop_index(op.f('ix_fa_admin_admins_created_at'), table_name='fa_admin_admins')
    op.drop_table('fa_admin_admins')
    op.drop_index(op.f('ix_fa_admin_sys_configs_value_type'), table_name='fa_admin_sys_configs')
    op.drop_index(op.f('ix_fa_admin_sys_configs_updated_at'), table_name='fa_admin_sys_configs')
    op.drop_index(op.f('ix_fa_admin_sys_configs_group_code'), table_name='fa_admin_sys_configs')
    op.drop_index(op.f('ix_fa_admin_sys_configs_created_at'), table_name='fa_admin_sys_configs')
    op.drop_index(op.f('ix_fa_admin_sys_configs_config_key'), table_name='fa_admin_sys_configs')
    op.drop_table('fa_admin_sys_configs')
    op.drop_index(op.f('ix_fa_admin_rules_updated_at'), table_name='fa_admin_rules')
    op.drop_index(op.f('ix_fa_admin_rules_status'), table_name='fa_admin_rules')
    op.drop_index(op.f('ix_fa_admin_rules_pid'), table_name='fa_admin_rules')
    op.drop_index(op.f('ix_fa_admin_rules_created_at'), table_name='fa_admin_rules')
    op.drop_table('fa_admin_rules')
    op.drop_index(op.f('ix_fa_admin_groups_updated_at'), table_name='fa_admin_groups')
    op.drop_index(op.f('ix_fa_admin_groups_status'), table_name='fa_admin_groups')
    op.drop_index(op.f('ix_fa_admin_groups_name'), table_name='fa_admin_groups')
    op.drop_index(op.f('ix_fa_admin_groups_created_at'), table_name='fa_admin_groups')
    op.drop_table('fa_admin_groups')
    # ### end Alembic commands ###
